name: UpdateArticle

on:
  push:
    branches: [ main ]
    paths:
      - 'SubMarkdown/*.md'

jobs:
  convert:
    permissions:
      contents: write
    uses: ./.github/workflows/convert.yml  

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        # cache: 'npm'

    - name: install gray-matter
      run: npm install gray-matter

    - name: install cheerio
      run: npm install marked cheerio

    - name: convert submarkdown to html
      run: node subconvert.js

    - name: Commit changes
      run: |
        git pull origin main --rebase
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update convert md & article links"
        git push